api_platform:
    mapping:
        paths:
            - '%kernel.project_dir%/src/Security/Entity'
            - '%kernel.project_dir%/src/Product/Entity'

    patch_formats:
        json: ['application/merge-patch+json']

    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header

    show_webby: false
    title: 'IX-API Framework'
    description: 'IX-API Implementation Framework for Internet Exchanges'
    version: '%app_version%'
