api_platform:
    mapping:
        paths:
            - '%kernel.project_dir%/src/Security/Entity'
            - '%kernel.project_dir%/src/ProductOffering/Entity'

    formats:
        json: ['application/json']
        jsonld: ['application/ld+json']
        html: ['text/html']
        jsonapi: ['application/vnd.api+json']

    patch_formats:
        json:     ['application/merge-patch+json']
        jsonapi:  ['application/vnd.api+json']

    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header

    collection:
        pagination:
            enabled: false

    title: 'IX-API Framework'
    description: 'IX-API Implementation Framework'
    version: '%app_version%'

    name_converter: Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter
    path_segment_name_generator: api_platform.path_segment_name_generator.dash
