doctrine:
    dbal:
        url: '%env(resolve:DATABASE_APP_URL)%'

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        mappings:
            App\Security\Entity:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Security/Entity'
                prefix: 'App\Security\Entity'
